name: gps_tracker
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  flutter_libserialport: ^0.5.0
  intl: ^0.20.2
  path_provider: ^2.1.1
  universal_io: ^2.2.0  # for platform detection (optional but useful)
  provider: ^6.1.5
  qr_flutter: ^4.1.0
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
